CREATE TABLE OPCAOCAFE
(
OPCAFE VARCHAR2(200) NOT NULL,
CONSTRAINT OPCAOCAFE_PK PRIMARY KEY (OPCAFE) ENABLE
)

CREATE TABLE COLABORADOR
(
NOME VARCHAR2(200) NOT NULL,
CPF VARCHAR2(11) NOT NULL,
OPCAFE_OPCAOCAFE VARCHAR2(200) NOT NULL,
CONSTRAINT COLABORADOR_PK PRIMARY KEY (CPF) ENABLE,
CONSTRAINT OPCAOCAFE_FK FOREIGN KEY (OPCAFE_OPCAOCAFE) REFERENCES OPCAOCAFE(OPCAFE) ENABLE
)
